library(arules)
library(arulesViz)
setwd("E:/Sem_3/Rprogramming/MODULE-3")
mydata<-read.transactions("aprioridata.csv",sep=',')
inspect(mydata)
a_rules<-apriori(mydata,list(support=0.04,confidence=0.2))
inspect(sort(a_rules,by="lift")[1:5])
plot(a_rules,method = "graph",measure = "confidence",shading = "lift")

getwd()
data<-read.transactions("single1.csv",format="single",sep=',',header = TRUE,cols=c("tid","items"))
inspect(data)
a_rules<-apriori(data,list(support=0.04,confidence=0.4))
inspect(sort(a_rules,by="lift")[1:5])
plot(a_rules,method = "graph",measure = "confidence",shading = "lift")
